name: FinalMachine

author: HiTech0926

description: 从FinalTech附属中提取出的原生快捷机器

main: com.hitech0926.finalmachine.FinalMachine

website: https://github.com/HiTech0926/FinalMachine/

version: ${project.version}

api-version: 1.17

depend:
- Slimefun
